language: python
sudo: required
python:
- '2.7'
env:
- TRAVIS_CI_BUILD=true
services:
- redis-server
before_script:
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
- echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' |
  sudo tee /etc/apt/sources.list.d/mongodb.list
- sudo apt-get update
- sudo apt-get install -y mongodb-org=2.6.6 mongodb-org-server=2.6.6 mongodb-org-shell=2.6.6
  mongodb-org-mongos=2.6.6 mongodb-org-tools=2.6.6
- sleep 15
- mongo --version
install:
- travis_retry pip install -r requirements-dev.txt
- travis_retry pip install tox>=2.1.1 coveralls
script:
- tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . )
after_success: coveralls --verbose
branches:
  only:
  - master
  - /^v.*$/
deploy:
  provider: pypi
  user: tcarel
  password:
    secure: KjaxWn13qxVGq8ka2LmFu3mdRyOjDR23KcdUNgPf8GJGQQI3RHHVaTXrpWASxQkV6DFYS0Xabcg9jhprMEKwdUJllHn92ecVaEadnTvgoM56pcgTvo8BpH1nJ9MX9i09V3xOUJuFZyGmh1fBkDYPKIxpwUsqryvu/SWxLMI8rt7P+z6X1HsucWs8y6aSw3a/iOtEzGZqDnSu3s/5zFyh6IgC2Rj1Zs/QQUWoFo8C2GLVk4qlLIDXoedB5q7zVWbbNOZuoGWeTOByCyp8Bx8XM9vdqG8qWVbVyIilE85ExWAU5W7cFz2bDqiqufW1pBax96FFD2dQ3TXfiy/xQdHgkc29trC2YxE8Qc52L2HhAU9jY2fDCxC8VSReMxdUFxze61EdEECon9a2t/GsZyW5oSD5iJp4V5SZbRi3Tl2ztVmO/Emb4vxuUIVdsLkNI5Jzf+A7W8vvNJyfkPPyV33CcsdSjD7U9Rke/uPg4Zz3MYYs7BDWiGcrGzNmxBtf2IZHMNwJ7lhuzgdY2y+oXa1/BtA+36DHeXs+fzT8nVL8L0d/18HjqTDgISZL8L9bBPXBRaOkyVLmxF/Uq4i4rygI8nOJ70TTUpkNKGUvl4zGB4982eyvdS3uztanJ2Sf7NDEWKjpO6kO8BVoLpKJWefGkC1IMbZ/RbkfF7j+NxuEZvM=
  on:
    tags: true
notifications:
  slack:
    secure: wEsybSQhs6kDluKeQlwrSPVjHmwm7yGK0zLl0h3UoWy0SnUzlOkr1JTgvbrRyFRbyG1dwy8Q78WCdYbdzted1mSKYXESsMN+rifaREsnzNj83Y7f5BqZyjN2kfnvVc8JjF6pWC39b2kPLtcNYqcYJfjFf6bn+Iccw+fnN2TY0bHF0GSUF7qHFK0qy3/u29B+k+gnDA8mzgTEbsI8gfHDC6xdzkavEiqi1oW4iD2IUpd6F4XYzBacwmyhXetJyxXPL26uSj2KUh9UwXiV9tAi6WM1L2ZvdYehG/iROUr1srOr7w8Y49mhU6k1yKbTHgihMpuQ+gMYd+aFLUFRB3dR0yxvZjaluNK5yCZoSoPOF9Gu65INNK1+bzwgYkgX9T0Su6reCUB3tS170gWsiByj3QuHl8yLmnGj6x/9SgE4FAHb7JJgObEtN0Bbht+81lFTJRISD7mGBtqwblMCw+UuVN7yyv29DAW1JJP79CZxie7DIjZDRtawwp7IDvJpzPs1rTOcr8jlzo3Haa/cbyGqN0rXXKwTWfdsloG/aEqOvkgFHcBWy1f6dzTh08Suw7frk/iTci0j2wFLWcyfZKqFQKWodA7yWb8nK1gPy0puSUBG2gMqyHCpqSVlu2cUTBPP4GxOClDJdH92aVacrPEBitODOQpQPmkmafFmBTy88n4=
