language: python
sudo: false
python:
- '2.7'
env:
- TRAVIS_CI_BUILD=true
services:
- redis-server
- rabbitmq
addons:
  apt:
    sources:
    - mongodb-upstart
    packages:
    - mongodb-org-server
    - mongodb-org-shell
    - rabbitmq-server
before_script:
- .tox/py27/bin/celery worker -Q backache,backache-quarantine -l WARNING -c1 -A tests.celery_worker
  &
install:
- travis_retry pip install -r requirements-dev.txt
- travis_retry pip install tox>=2.1.1 coveralls
- tox --notest
script:
- tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . )
after_success: coveralls --verbose
branches:
  only:
  - master
  - /^v.*$/
deploy:
  provider: pypi
  user: tcarel
  password:
    secure: of5FHXlCnFSdxB4y3hvR7l6m3rU6Sq7x3yekfcnUSVE9bvmI+q93tZwiJ+LCNNjDXhGG/w1zG9PjHNlWFiHqNE2dNCzIUhTgkr8DgjoL+Q7HYJJ3wepxW/Zs0A4EYHCIWesKyyeLHKigd7jnq9Kig8pl7ptidjh2JzNNSbpqZBMS1pg1VjSJpv8uiqfLmwc2UoU6U6ZvpVHT01UtI2nseFClObFkfRS6FIAirWDbWwY7hcWF+EdVK2iNVdYXt5AzvsxOs5ymqHXSJCGoggTGgHS2ACPi3zYsE60DQ1QIkHo/sqefNXW9PR13Y8gWyFEYfeeK5CFbo+6pjBYvevrII83QoIwjS4tNiMjdOJngoFc91Z2kKgo1SeA2kSa86x+GDrR7KFRFyEJoIea+JWrqZAUW6lyLGb3wnyhyjsFm5g8aj7ZWRFDneQcgWo1l5drfHBpd156cY8CrBIeKn7POZGlG5CfQToqJALhWMdYLjqXwf68CsyZp4228pBXY1spL6FiAxw1lwPJIf0uYol+uVuyHzgrnlEwdYiyiSPjbV1/IVhp2jLQBWKkwMoc3TFui3YlN8wx5F3OBlw4+wkwbQhMnrd4gcoxFv/0AVm77jEXKifBK4Di9oAuPfVxlvi21bML3hiSEqqkqYwaabSoerWQ7cnTXagkfh9SCMavyBy0=
  on:
    tags: true
    repo: cogniteev/backache
notifications:
  slack:
    secure: iQUKnGXx5axfGoHxqVtAnEBqlMbzZrD7C7zu3jZMuLyHllUHsrCDTwDeDHUNZFarKhDEOluD3RFHxHgct3RUJih+GV7+mB4GXWy7787uGJcIsZ65L29wfio373y7KiaB4rB+4cGpbQLcTX8peE0u3Z1ODeR0+Ynm3oxjf5u25T5zMGvrCUBXanYLDYjPYh5JOlXZKcm0w1C7fIQG7lHpSwdD6t02maMOUVdBlT5SMdUvILVLWtHBW4rHvGrQoPQPgbET3DxcT9736/Of1NhvFs0eFn0UU8ZR2Zs6G5n8a2JEFje7e/q3aYvYi9y0eyScDSYAQHVlX+inK86Qd+VUh87DtpJsZ/M34jCyk3rJLIs5pxXvvmDnOH6qQQhkKjhRxM+Wk5FRlcGg3Wdrl2a+G4GCSZy7D+gdi1Sci8V9Kx/aXCmxfNcy0T381sQQD6//WgXiUyjYSGy7hxmuc4sTMsF4yVBxC+wE7LLpjMYXEEnVw4XqZm9e2sc4SNb4Y/XhAuF6e8SPFwlXGFCK1/CHSxjH9d9+eWVuLND8gLXhQf/+Cbhetorx0AGi6TDFu4qzTBEC/uvPG/w+TIZ11gQLofWqdNxs8EW98jiUa3Qq0FKOvDi6KaN0RsVuHLfeyOhoeCv6CamIMafV2LCHgjK4hKDVsILMRgsrMd8Ig4UwGR4=
