language: python
sudo: false
python:
- '2.7'
env:
- TRAVIS_CI_BUILD=true
services:
- redis-server
- rabbitmq
addons:
  apt:
    sources:
      - mongodb-upstart
    packages:
      - mongodb-org-server
      - mongodb-org-shell
      - rabbitmq-server
before_script:
- mongo --version
install:
- travis_retry pip install -r requirements-dev.txt
- travis_retry pip install tox>=2.1.1 coveralls
- tox --notest
before_script:
- .tox/py27/bin/celery worker -Q backache,backache-quarantine -l WARNING -c1 -A tests.celery_worker &
script:
- tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . )
after_success: coveralls --verbose
branches:
  only:
  - master
  - /^v.*$/
deploy:
  provider: pypi
  user: tcarel
  password:
    secure: of5FHXlCnFSdxB4y3hvR7l6m3rU6Sq7x3yekfcnUSVE9bvmI+q93tZwiJ+LCNNjDXhGG/w1zG9PjHNlWFiHqNE2dNCzIUhTgkr8DgjoL+Q7HYJJ3wepxW/Zs0A4EYHCIWesKyyeLHKigd7jnq9Kig8pl7ptidjh2JzNNSbpqZBMS1pg1VjSJpv8uiqfLmwc2UoU6U6ZvpVHT01UtI2nseFClObFkfRS6FIAirWDbWwY7hcWF+EdVK2iNVdYXt5AzvsxOs5ymqHXSJCGoggTGgHS2ACPi3zYsE60DQ1QIkHo/sqefNXW9PR13Y8gWyFEYfeeK5CFbo+6pjBYvevrII83QoIwjS4tNiMjdOJngoFc91Z2kKgo1SeA2kSa86x+GDrR7KFRFyEJoIea+JWrqZAUW6lyLGb3wnyhyjsFm5g8aj7ZWRFDneQcgWo1l5drfHBpd156cY8CrBIeKn7POZGlG5CfQToqJALhWMdYLjqXwf68CsyZp4228pBXY1spL6FiAxw1lwPJIf0uYol+uVuyHzgrnlEwdYiyiSPjbV1/IVhp2jLQBWKkwMoc3TFui3YlN8wx5F3OBlw4+wkwbQhMnrd4gcoxFv/0AVm77jEXKifBK4Di9oAuPfVxlvi21bML3hiSEqqkqYwaabSoerWQ7cnTXagkfh9SCMavyBy0=
  on:
    tags: true
    repo: cogniteev/backache
notifications:
  slack:
    secure: wEsybSQhs6kDluKeQlwrSPVjHmwm7yGK0zLl0h3UoWy0SnUzlOkr1JTgvbrRyFRbyG1dwy8Q78WCdYbdzted1mSKYXESsMN+rifaREsnzNj83Y7f5BqZyjN2kfnvVc8JjF6pWC39b2kPLtcNYqcYJfjFf6bn+Iccw+fnN2TY0bHF0GSUF7qHFK0qy3/u29B+k+gnDA8mzgTEbsI8gfHDC6xdzkavEiqi1oW4iD2IUpd6F4XYzBacwmyhXetJyxXPL26uSj2KUh9UwXiV9tAi6WM1L2ZvdYehG/iROUr1srOr7w8Y49mhU6k1yKbTHgihMpuQ+gMYd+aFLUFRB3dR0yxvZjaluNK5yCZoSoPOF9Gu65INNK1+bzwgYkgX9T0Su6reCUB3tS170gWsiByj3QuHl8yLmnGj6x/9SgE4FAHb7JJgObEtN0Bbht+81lFTJRISD7mGBtqwblMCw+UuVN7yyv29DAW1JJP79CZxie7DIjZDRtawwp7IDvJpzPs1rTOcr8jlzo3Haa/cbyGqN0rXXKwTWfdsloG/aEqOvkgFHcBWy1f6dzTh08Suw7frk/iTci0j2wFLWcyfZKqFQKWodA7yWb8nK1gPy0puSUBG2gMqyHCpqSVlu2cUTBPP4GxOClDJdH92aVacrPEBitODOQpQPmkmafFmBTy88n4=
